Allow skipping sequential versions with author-approval criteria
JuliaRegistries/RegistryCI.jl pull request #539
Opened 2024-01-27 21:32 UTC by ericphanson

Based on #536 to avoid conflicts. That one should be merged first.

Requires https://github.com/JuliaRegistries/General/pull/98815

The flow here is:

* automerge comments, notes they can override
* package author comments "merge approved"
* GHA adds a label
* new label triggers automerge again
* automerge sees the new label and skips the sequential version check

FAQ:
* What happens if some one else comments "merge approved"? The label doesn't get applied, so nothing happens
* What happens if someone adds the label manually? The label does take effect. I.e. triage-level maintainers can facilitate author approval if needed. We need to trust them to not abuse this (I doubt it will happen and we can revoke triage access if folks aren't behaving)
* Does a "merge approved" comment block automerge unless it contains `[noblock]`? No, we special case it so comments that trigger author-approval count as noblock.
* Does AutoMerge's comment mentioning "merge approved" trigger the labelling workflow? No, it shouldn't, it is a bot user. (If it did, the label would still not be applied, since the registrator is not the package author)
* What happens if multiple guidelines use the author-approval mechanism, does the author have to indicate what they are approving? No, `merge approved` will apply to all of them
* What happens if the author comments before even seeing the automerge comment? They would end up approving whatever it says, but only 1 guideline is overridable at this point.

2024-01-28 14:19 UTC, DilumAluthge commented
> * GHA adds a label
> * new label triggers automerge again

This might be a problem. If the label was added using the default `GITHUB_TOKEN` token, then IIRC the "label-added" event won't trigger any further GitHub Actions.

2024-01-28 14:31 UTC, DilumAluthge commented
> > * GHA adds a label
> > * new label triggers automerge again
> 
> This might be a problem. If the label was added using the default `GITHUB_TOKEN` token, then IIRC the "label-added" event won't trigger any further GitHub Actions.

Can we make the "GHA adds a label" step use the custom `@JuliaTagBot` PAT we have? I believe that this would bypass the above issue.

Of course, maybe we should first verify that the above actually would be an issue.

2024-01-28 14:32 UTC, DilumAluthge commented
Perhaps we should make the text specific to the guideline being approved? How about something like `/approve-merge-skip-version`?

Also, how about we add the `/` to the front, to emphasize that this is kind of a "command" that the package author is providing?

2024-01-28 14:33 UTC, DilumAluthge commented
Even if we only get this working for GitHub-hosted packages at first, this still covers the majority of packages, so I still think it'll help reduce the manual registry-committer burden.

2024-01-28 14:45 UTC, ericphanson commented
> This might be a problem. If the label was added using the default GITHUB_TOKEN token, then IIRC the "label-added" event won't trigger any further GitHub Actions.

Good point, I think that sounds right.

> Can we make the "GHA adds a label" step use the custom @JuliaTagBot PAT we have? I believe that this would bypass the above issue.
> Of course, maybe we should first verify that the above actually would be an issue.

Yeah, that makes sense. Since this can be done on the GHA by itself, IMO we can work on that once we merge down the stuff here and get RegistryCI updated on General. Then we can try it out and get the authentication working there.

> Perhaps we should make the text specific to the guideline being approved? How about something like /approve-merge-skip-version?
> Also, how about we add the / to the front, to emphasize that this is kind of a "command" that the package author is providing?

To me this seems overly complicated. Since RegistryCI prints all of the problems it found at once, the author can either approve merging or not knowing that information. I don't really feel like there's more than 1 decision the author actually has, since not approving 1 thing blocks merging (so ultimately they need to decide if they want to merge now or not).

I also think this will lead to more questions/issues where folks approve 1 thing but not another and are confused.

I think "merge approved" is straightforward and simpler.

> Even if we only get this working for GitHub-hosted packages at first, this still covers the majority of packages, so I still think it'll help reduce the manual registry-committer burden.

Agreed!

2024-01-28 14:48 UTC, ericphanson commented
Re- the token, the [docs here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) seem clear that indeed `GITHUB_TOKEN` is insufficient for this, and we should use a PAT. We could use an existing one or make a new one for the task.

2024-01-28 14:51 UTC, DilumAluthge commented
> We could use an existing one or make a new one for the task.

For now, probably easier to re-use the existing one (the `@JuliaTagBot` token that AutoMerge uses when merging a PR). But we might consider making a new one in the future.

2024-01-29 00:10 UTC, DilumAluthge requested changes

2024-01-29 00:10 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +    "write a comment that says \"merge approved\".**")
```suggestion
    "write a comment that says `[merge approved]`.**")
```

2024-01-29 00:11 UTC, DilumAluthge commented on src/AutoMerge/cron.jl
> +    not_blocking = occursin("[noblock]", body(c)) || occursin("merge approved", lowercase(body(c)))
As discussed in https://github.com/JuliaRegistries/General/pull/98815, we're going to compromise, and we'll require `[merge approved]`, but not require `[noblock]`.

2024-01-29 00:11 UTC, ericphanson commented on src/AutoMerge/util.jl
> +const AUTHOR_APPROVED_LABEL = "package-author-approved"
```suggestion
const AUTHOR_APPROVED_LABEL = "Override AutoMerge: package author approved"
```

2024-01-29 00:11 UTC, ericphanson commented on test/automerge-unit.jl
> +        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="package-author-approved")])
```suggestion
        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="Override AutoMerge: package author approved")])
```

2024-01-29 00:11 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +    "write a comment that says \"merge approved\".**")
We will do https://github.com/JuliaRegistries/RegistryCI.jl/pull/539#discussion_r1468970719 instead.

2024-01-29 00:12 UTC, ericphanson commented on test/automerge-unit.jl
> +        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="hi"), GitHub.Label(; name="package-author-approved")])
```suggestion
        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="hi"), GitHub.Label(; name="Override AutoMerge: package author approved")])
```

2024-01-29 00:12 UTC, ericphanson commented on src/AutoMerge/guidelines.jl
> +    "write a comment that says \"merge approved\".**")
```suggestion
    "write a comment that contains the text: `[merge approved]`.**")
```

2024-01-29 00:13 UTC, ericphanson commented on example_github_workflow_files/automerge.yml
> +    if: "${{  github.event.action != 'labeled' || (github.event.action == 'labeled' && (github.event.label.name == 'Override AutoMerge: name similarity is okay' || github.event.label.name == 'package
```suggestion
    if: "${{  github.event.action != 'labeled' || (github.event.action == 'labeled' && (github.event.label.name == 'Override AutoMerge: name similarity is okay' || github.event.label.name == 'Override AutoMerge: package author approved')) }}"
```

2024-01-29 00:14 UTC, ericphanson commented on test/automerge-unit.jl
> +        @test !AutoMerge.pr_comment_is_blocking(GitHub.Comment(; body="merge approved abc"))
```suggestion
        @test !AutoMerge.pr_comment_is_blocking(GitHub.Comment(; body="[merge approved] abc"))
```

2024-01-29 00:34 UTC, DilumAluthge requested changes

2024-01-29 00:34 UTC, DilumAluthge commented on docs/src/guidelines.md
> +        author_approved = false
```suggestion
        author_approved = false,
```

2024-01-29 00:34 UTC, DilumAluthge commented on docs/src/guidelines.md
> +        author_approved = false
```suggestion
        author_approved = false,
```

2024-01-29 00:34 UTC, DilumAluthge commented on src/AutoMerge/cron.jl
> +    not_blocking = occursin("[noblock]", body(c)) || occursin("merge approved", lowercase(body(c)))
```suggestion
    not_blocking = occursin("[noblock]", body(c)) || occursin("[merge approved]", lowercase(body(c)))
```

2024-01-29 13:30 UTC, DilumAluthge commented
@ericphanson This needs a rebase, I think.

2024-01-29 17:42 UTC, ericphanson commented
(updated)

2024-01-29 21:04 UTC, DilumAluthge requested changes

2024-01-29 21:04 UTC, DilumAluthge commented on example_github_workflow_files/automerge.yml
> +    if: "${{  github.event.action != 'labeled' || (github.event.action == 'labeled' && (github.event.label.name == 'Override AutoMerge: name similarity is okay' || github.event.label.name == 'Overrid
```suggestion
    if: "${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && (github.event.label.name == 'Override AutoMerge: name similarity is okay' || github.event.label.name == 'Override AutoMerge: package author approved')) }}"
```

2024-01-29 21:24 UTC, DilumAluthge commented on docs/src/guidelines.md
> +        author_approved = false,
```suggestion
        package_author_approved = false,
```

2024-01-29 21:24 UTC, DilumAluthge commented on docs/src/guidelines.md
> +        author_approved = false,
```suggestion
        package_author_approved = false,
```

2024-01-29 21:25 UTC, DilumAluthge commented on src/AutoMerge/cron.jl
> +    # Note: `merge_approved` is not case sensitive, to match the semantics of `contains` on GHA
```suggestion
    # Note: `[merge approved]` is not case sensitive, to match the semantics of `contains` on GitHub Actions
```

2024-01-29 21:26 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +    author_approved::Bool # currently unused for new packages
```suggestion
    package_author_approved::Bool # currently unused for new packages
```

2024-01-29 21:26 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +    author_approved::Bool
```suggestion
    package_author_approved::Bool,
```

2024-01-29 21:26 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +        (guideline_sequential_version_number, !this_pr_can_use_special_jll_exceptions && !author_approved),
```suggestion
        (guideline_sequential_version_number, !this_pr_can_use_special_jll_exceptions && !package_author_approved),
```

2024-01-29 21:26 UTC, DilumAluthge commented on src/AutoMerge/pull_requests.jl
> +        author_approved=has_author_approved_label(data.pr.labels)
```suggestion
        package_author_approved=has_package_author_approved_label(data.pr.labels)
```

2024-01-29 21:26 UTC, DilumAluthge commented on src/AutoMerge/util.jl
> +const AUTHOR_APPROVED_LABEL = "Override AutoMerge: package author approved"
```suggestion
const PACKAGE_AUTHOR_APPROVED_LABEL = "Override AutoMerge: package author approved"
```

2024-01-29 21:27 UTC, DilumAluthge commented on src/AutoMerge/util.jl
> +function has_author_approved_label(labels)
```suggestion
function has_package_author_approved_label(labels)
```

2024-01-29 21:27 UTC, DilumAluthge commented on src/AutoMerge/util.jl
> +        if label.name === AUTHOR_APPROVED_LABEL
```suggestion
        if label.name === PACKAGE_AUTHOR_APPROVED_LABEL
```

2024-01-29 21:27 UTC, DilumAluthge commented on src/AutoMerge/util.jl
> +            @debug "Found `$(AUTHOR_APPROVED_LABEL)` label"
```suggestion
            @debug "Found `$(PACKAGE_AUTHOR_APPROVED_LABEL)` label"
```

2024-01-29 21:27 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +const AUTHOR_APPROVAL_INSTRUCTIONS = string(
```suggestion
const PACKAGE_AUTHOR_APPROVAL_INSTRUCTIONS = string(
```

2024-01-29 21:27 UTC, DilumAluthge commented on src/AutoMerge/guidelines.jl
> +        AUTHOR_APPROVAL_INSTRUCTIONS,
```suggestion
        PACKAGE_AUTHOR_APPROVAL_INSTRUCTIONS,
```

2024-01-29 21:29 UTC, DilumAluthge commented on test/automerge-unit.jl
> +        @test !AutoMerge.has_author_approved_label(nothing)
```suggestion
        @test !AutoMerge.has_package_author_approved_label(nothing)
```

2024-01-29 21:29 UTC, DilumAluthge commented on test/automerge-unit.jl
> +        @test !AutoMerge.has_author_approved_label([GitHub.Label(; name="hi")])
```suggestion
        @test !AutoMerge.has_package_author_approved_label([GitHub.Label(; name="hi")])
```

2024-01-29 21:29 UTC, DilumAluthge commented on test/automerge-unit.jl
> +        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="Override AutoMerge: package author approved")])
```suggestion
        @test AutoMerge.has_package_author_approved_label([GitHub.Label(; name="Override AutoMerge: package author approved")])
```

2024-01-29 21:29 UTC, DilumAluthge commented on test/automerge-unit.jl
> +        @test AutoMerge.has_author_approved_label([GitHub.Label(; name="hi"), GitHub.Label(; name="Override AutoMerge: package author approved")])
```suggestion
        @test AutoMerge.has_package_author_approved_label([GitHub.Label(; name="hi"), GitHub.Label(; name="Override AutoMerge: package author approved")])
```

2024-01-30 00:08 UTC, merged